### ISSUE TITLE
通信录页面一些小问题

### ISSUE THREAD

**Issue by rty813** [kidozh/NpuHelper#2]
1. listView没有增加滑动条，无法看到当前的滑动位置
2. 建议增加搜索功能

**Comment by kidozh** [comment]
> 1. listView没有增加滑动条，无法看到当前的滑动位置
> 2. 建议增加搜索功能

在新上传的commit里面针对大多数的recyclerview都给上了滑动条 [add scrollbar for most recyclerview](https://github.com/kidozh/NpuHelper/commit/66fd7bfc4ff83d56799a9e39cc6fc5784fc116fd)

搜索功能不知道你说的是不是通用里面增加，在第二个tab里面是有搜索框的。

**Comment by rty813** [comment]
好的
