### ISSUE TITLE
主页面打开速度过慢

### ISSUE THREAD

**Issue by rty813** [kidozh/NpuHelper#3]
1、是否在onCreate函数中执行了过多的阻塞任务，导致开启速度过慢。建议，要么减少耗时操作，要么加入启动页，更友好。
2、刚打开的时候提示无法与服务器通信，是什么原因呢？

**Comment by kidozh** [comment]
之前排查代码并没有发现此类问题，后来在GFW环境下复现了此BUG，我对定位服务进行了修改。

定位编码模块使用高德地图对Google自带的定位服务进行了取代，经发现，目前冷启动速度已经得到了相应的改善。

非常感谢你的建议。
